# Load shared files
source("FirstStage.R")
source ("RemoveControls.R")
source("Estimators.R")
source("LastStage.R")
source("JM_funs.R")
source("to.Latex.R")
# Load Dom's specific files
#source("Process.R")
source("Support.R")
source("DML.R")
source("FirstStageJJFoods.R")
source("SecondStage.R")
source("BoxWhiskerPlot.R")
source("PriceToTreats.R")
source("Initialize.R")
source("PriceToTreats.R")
source("CrossPriceFunctions.R")
source("CleanData.R")
source("FinalStage.R")
source("Main.R")
source("RunCrossPrice.R")
source("FindMyLevel.R")
source("Histogram.R")
source("CompareOLSRidge.R")
# Load libraries
library(tictoc)

library(ggplot2)
library(dplyr)
library(plyr)
library(reshape2)
library(glmnet)
library(tidyr)
library(iterators)
library(assertthat)
#library(tidyverse)
library(rmutil)
library(xtable)
library(glmnet)
library(gamlr)
library(foreach)
library(expm)
library(flare)
library(Matrix)
library(parallel)
library(xtable)
#library(doMC)
